import {World, Vec3} from "cannon-es";

function createPhysicSystem({gravity = {x: 0, y: -9.82, z: 0}} = {}) {
    const world = new World({
        gravity: new Vec3(gravity.x, gravity.y, gravity.z), // m/s²
    });

    // --- 🔧 Add minimal collision-exit tracking ---
    // -- generated by chatgpt because somehow the cannon-es's team can't bother to add this simple thing to bodies -- //
    const previousPairs = new Set();
    const currentPairs = new Set();

    // Monkey-patch the world.step function
    const _step = world.step.bind(world);
    world.step = function (...args) {
        // --- Before step: clear currentPairs ---
        currentPairs.clear();

        // Run original step (this fills world.contacts)
        _step(...args);
        // build pairs for this frame
        for (const contact of world.contacts) {
            const a = contact.bi;
            const b = contact.bj;
            const key = [a.id, b.id].sort().join("-");
            currentPairs.add(key);
        }

        // detect exited pairs
        for (const key of previousPairs) {
            if (!currentPairs.has(key)) { // if a current contact Pair doesn't have a register contact anymore from the previous step then
                const [idA, idB] = key.split("-").map(Number); // we retrieve the id of the two bodies by splitting the key string
                const a = world.bodies.find(b => b.id === idA);
                const b = world.bodies.find(b => b.id === idB);
                // we give for each body a event "collideExit" that say witch body has existed the contact
                if (a?._listeners?.collideExit)
                    a._listeners.collideExit.forEach(fn => fn.call(a, { body: b })); // body b has stop colliding
                if (b?._listeners?.collideExit)
                    b._listeners.collideExit.forEach(fn => fn.call(b, { body: a })); // body a has stop colliding
            }
        }

        // swap sets
        previousPairs.clear(); // we clear the previous Pairs
        currentPairs.forEach(k => previousPairs.add(k)); // all current contact pairs are now previous contact pairs
        currentPairs.clear(); // we clear the current Pairs for the next step
    };

    // Give bodies local listener API
    const _addBody = world.addBody.bind(world);
    world.addBody = (body) => {
        if (!body._listeners) body._listeners = {};
        body.addEventListener = function (type, fn) {
            if (!this._listeners[type]) this._listeners[type] = [];
            this._listeners[type].push(fn);
        };
        body.removeEventListener = function (type, fn) {
            const list = this._listeners[type];
            if (!list) return;
            const i = list.indexOf(fn);
            if (i !== -1) list.splice(i, 1);
        };
        _addBody(body);
    };

    return world;
}

export {createPhysicSystem};